# Generated by Django 2.1.5 on 2019-02-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittertweets',
            name='content',
            field=models.CharField(max_length=280),
        ),
    ]
