# Generated by Django 2.1.7 on 2019-03-07 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_profile_name', models.CharField(max_length=255)),
                ('user_password', models.CharField(default='**********', max_length=255)),
                ('user_first_name', models.CharField(max_length=255)),
                ('user_last_name', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('user_phone', models.CharField(max_length=255)),
                ('user_country', models.CharField(max_length=255)),
                ('user_city', models.CharField(max_length=255)),
                ('user_website', models.CharField(max_length=500)),
                ('tweet_count', models.IntegerField(default=0)),
                ('follower_count', models.IntegerField(default=0)),
                ('liked_tweet_count', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile_picture', models.ImageField(blank=True, default='profile_image/default_user.png', upload_to='profile_image')),
                ('about_user', models.TextField(max_length=255)),
            ],
        ),
    ]
