# Generated by Django 2.1.5 on 2019-02-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_profile_name', models.CharField(max_length=255)),
                ('user_password', models.CharField(default='************', max_length=255)),
            ],
        ),
    ]
