# Generated by Django 2.1.5 on 2019-02-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='user_password',
            field=models.CharField(max_length=255),
        ),
    ]
