# Generated by Django 2.1.7 on 2019-03-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_encryption_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='user_mails',
            field=models.IntegerField(default=0),
        ),
    ]
