# Generated by Django 2.1.5 on 2019-02-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190214_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='liked_tweet_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='tweet_count',
            field=models.IntegerField(default=0),
        ),
    ]
