# Generated by Django 2.1.7 on 2019-03-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190320_1445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_encryption_list',
            new_name='user_encryption_key_list',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='user_encrypt_key',
        ),
    ]
