# Generated by Django 2.1.7 on 2019-03-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190320_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_encryption_key_list',
            name='encrypt_list_owner',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user_encryption_key_list',
            name='enc_keys_notes',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user_encryption_key_list',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user_encryption_key_list',
            name='user_profile_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
