# Generated by Django 2.1.7 on 2019-03-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190320_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_encryption_key_list',
            name='key_id',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
