# Generated by Django 2.1.7 on 2019-04-03 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_user_id', models.CharField(blank=True, max_length=255)),
                ('blocked_by', models.CharField(blank=True, max_length=255)),
                ('block_id', models.CharField(blank=True, max_length=255)),
                ('block_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FollowingUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_user', models.CharField(blank=True, max_length=255)),
                ('liked_by_user', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LikedTweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(blank=True, max_length=255)),
                ('tweet_id', models.CharField(blank=True, max_length=255)),
                ('liked_by_user', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PinnedPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_by_user', models.CharField(blank=True, max_length=255)),
                ('tweet_id', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_message_id', models.CharField(blank=True, max_length=255)),
                ('source_author_id', models.CharField(blank=True, max_length=255)),
                ('target_user_id', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(default=None, max_length=280)),
                ('sent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('media_attachment', models.ImageField(blank=True, default='default.png', upload_to='private_message_images')),
                ('seen', models.BooleanField(default=False)),
                ('show_message', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepliesToTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(blank=True, max_length=255)),
                ('author_id', models.CharField(blank=True, max_length=255)),
                ('reply_id', models.CharField(blank=True, max_length=255)),
                ('content', models.CharField(default=None, max_length=280)),
                ('media_attachment', models.ImageField(blank=True, default='default.png', upload_to='site_media')),
                ('reply_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(default=None, max_length=140)),
                ('encrypted_content', models.TextField(blank=True, max_length=280)),
                ('content_key', models.CharField(blank=True, max_length=255)),
                ('encrypt_content', models.BooleanField(default=False)),
                ('author_id', models.CharField(blank=True, max_length=255)),
                ('replies', models.BigIntegerField(default=0)),
                ('favourites', models.IntegerField(default=0)),
                ('published', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('media_attachment', models.ImageField(blank=True, default='default.png', upload_to='site_media')),
                ('show_post', models.BooleanField(default=True)),
                ('show_encrypted', models.BooleanField(default=False)),
            ],
        ),
    ]
