# Generated by Django 2.1.7 on 2019-03-07 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Following_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_user', models.CharField(blank=True, max_length=255)),
                ('liked_by_user', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Liked_Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(blank=True, max_length=255)),
                ('tweet_id', models.CharField(blank=True, max_length=255)),
                ('liked_by_user', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Replied_To_Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Twitter_Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(default=None, max_length=280)),
                ('author_id', models.CharField(blank=True, max_length=255)),
                ('reply_id', models.CharField(blank=True, max_length=255)),
                ('replies', models.BigIntegerField(default=0)),
                ('favourites', models.IntegerField(default=0)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('media_attachment', models.ImageField(blank=True, default='default.png', upload_to='site_media')),
            ],
        ),
    ]
