# Generated by Django 2.1.7 on 2019-03-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter_tweet',
            name='content_encrypt',
            field=models.TextField(blank=True, max_length=280),
        ),
    ]
