# Generated by Django 2.1.5 on 2019-02-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittertweets',
            name='favourites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twittertweets',
            name='replies',
            field=models.BigIntegerField(default=0),
        ),
    ]
