# Generated by Django 2.1.7 on 2019-03-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinned_Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_by_user', models.CharField(blank=True, max_length=255)),
                ('tweet_id', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
