# Generated by Django 2.1.7 on 2019-03-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190307_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_message',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twitter_tweet',
            name='coentent_crypt',
            field=models.BooleanField(default=False),
        ),
    ]
