# Generated by Django 2.1.7 on 2019-03-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190314_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitter_tweet',
            old_name='coentent_crypt',
            new_name='encrypt_content',
        ),
    ]
