# Generated by Django 2.1.7 on 2019-03-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190314_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter_tweet',
            name='media_attachment',
            field=models.ImageField(blank=True, default='site_media/default.png', upload_to='site_media'),
        ),
    ]
