# Generated by Django 2.1.7 on 2019-03-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190317_0837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Replied_To_Tweet',
            new_name='Replies_To_Tweet',
        ),
    ]
