# Generated by Django 2.1.7 on 2019-03-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_private_message_media_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='private_message',
            old_name='date',
            new_name='sent_date',
        ),
    ]
