# Generated by Django 2.1.7 on 2019-03-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190318_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='private_message',
            name='media_attachment',
            field=models.ImageField(blank=True, default='default.png', upload_to='private_message_images'),
        ),
    ]
