# Generated by Django 2.1.7 on 2019-03-19 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190318_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitter_tweet',
            old_name='content_encrypt',
            new_name='encrypted_content',
        ),
    ]
