# Generated by Django 2.1.7 on 2019-03-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190318_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_message',
            name='private_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
