# Generated by Django 2.1.7 on 2019-03-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190320_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter_tweet',
            name='show_post',
            field=models.BooleanField(default=True),
        ),
    ]
