# Generated by Django 2.1.7 on 2019-03-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_twitter_tweet_show_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_message',
            name='show_message',
            field=models.BooleanField(default=True),
        ),
    ]
