# Generated by Django 2.1.7 on 2019-03-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_private_message_show_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter_tweet',
            name='show_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
