# Generated by Django 2.1.7 on 2019-03-22 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190320_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies_to_tweet',
            name='media_attachment',
            field=models.ImageField(blank=True, default='default.png', upload_to='site_media'),
        ),
        migrations.AddField(
            model_name='replies_to_tweet',
            name='reply_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='replies_to_tweet',
            name='content',
            field=models.CharField(default=None, max_length=280),
        ),
    ]
