# Generated by Django 2.1.7 on 2019-03-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190320_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies_to_tweet',
            name='media_attachment',
            field=models.ImageField(blank=True, default='default.png', upload_to='site_media'),
        ),
    ]
