# Generated by Django 2.1.7 on 2019-03-21 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_replies_to_tweet_media_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies_to_tweet',
            name='reply_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
