# Generated by Django 2.1.7 on 2019-03-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_replies_to_tweet_reply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies_to_tweet',
            name='content',
            field=models.CharField(default=None, max_length=280),
        ),
    ]
